clear
close all
clc

%% ================================================================
%  3D RECTANGULAR FEniCS POST-PROCESSING -- THESIS-READY
%
%  Designed for the restartable 3D rectangular H(div) calculation.
%
%  Main outputs:
%    * stitched concentration output across ALL restart segments
%    * full-range concentration slices, 0 <= c <= 1
%    * high-contrast concentration slices, user-set fixed contrast <= c <= 1
%    * per-time normalised concentration slices, 0 <= c_N <= 1
%    * x-z and y-z velocity streamlines at selected times
%    * full-tank and central-region horizontal averages
%    * normalised vertical fresh-water profiles
%    * absolute / contrast / normalised time-height maps
%    * final-time x-y plan slices
%    * fresh-water volume versus time
%    * MAT and CSV exports
%
%  IMPORTANT:
%  Run this script from either:
%
%    (a) the overall result root containing:
%          segments/segment_.../c_hdiv_v2.xdmf
%
%        -> ALL restart segments are found, sorted and de-duplicated
%
%    OR
%
%    (b) a single segment folder containing c_hdiv_v2.xdmf
%
%        -> only that segment is processed.
%
%  The file called u_hdiv_v2.xdmf in the production simulation stores
%  the accepted Taylor-Hood velocity used for visualisation.  The H(div)
%  reconstruction remains the conservative scalar-advection flux.



%% ================================================================
%  USER SETTINGS


dataRoot = pwd;

% Physical tank dimensions.
L = 0.600;
W = 0.300;
H = 0.200;

xMinExpected = -L/2;
xMaxExpected =  L/2;
yMinExpected = -W/2;
yMaxExpected =  W/2;
zMinExpected = 0.0;
zMaxExpected = H;


% Thesis concentration settings


% The production concentration is already physically normalised:
%   c = 0 : fresh water
%   c = 1 : saline ambient
%
% Full-range images therefore use [0,1].
%
% The contrast images deliberately show only the upper concentration
% range.  This is the version that reveals the weak ceiling layer.
contrastLower = 0.85;

% Concentration snapshots every 0.5 s.
sliceTimeSpacing = 0.5;

% Mean-profile curves every 3 s.
% For an 18 s run this naturally gives:
%   3, 6, 9, 12, 15, 18 s
profileTimeSpacing = 3.0;

% Velocity streamlines every 2 s.
streamlineTimeSpacing = 2.0;


% Horizontal averaging


% 50 bins -> dz = 4 mm.
% This is deliberately coarser than the smallest local mesh spacing.
nZBins = 50;

% Central plume-focused region: 6 cm x 6 cm.
centralHalfWidthX = 0.030;
centralHalfWidthY = 0.030;


% Visual slices


% Concentration is cell-centred DG0.  Thin slabs are therefore used
% only for visual interpolation, not for quantitative averaging.
sliceHalfThicknessXZ = 0.008;     % |y| <= 8 mm
sliceHalfThicknessYZ = 0.008;     % |x| <= 8 mm
sliceHalfThicknessXY = 0.006;     % final x-y plan views

% Velocity visualisation is nodal.  Use a slightly thinner central slab.
velocitySliceHalfThickness = 0.006;

% Plot grids.
nxXZ = 900;
nzXZ = 300;

nyYZ = 600;
nzYZ = 400;

nxXY = 900;
nyXY = 450;

% Final-time horizontal plan views.
planZFractions = [0.25 0.50 0.75 0.95];

% Streamline density.
streamlineDensity = 1.15;

% Fixed velocity-magnitude display range for comparison between times.
% The discrete inlet peak is ~0.2132 m/s.
velocityDisplayMax = 0.22;

% Output resolution.
pngResolution = 400;
thesisPngResolution = 600;


% Time-height display interpolation

%
% Horizontal averages are STILL calculated from the original
% volume-weighted DG0 data and saved unchanged to MAT/CSV.
%
% This setting affects ONLY the plotted time-height images.  The
% binned values are linearly interpolated onto a finer display grid
% so the thesis figures do not appear as blocky horizontal strips.
smoothTimeHeightForDisplay = true;
nZTimeHeightDisplay = 350;


%% ================================================================
%  OUTPUT FOLDERS


contrastTag = strrep(sprintf('%.2f',contrastLower),'.','p');

resultsFolder = fullfile( ...
    dataRoot, ...
    'MATLAB_3D_rectangular_postprocessing_thesis_ready');

if ~exist(resultsFolder,'dir')
    mkdir(resultsFolder)
end

% Concentration folders.
xzFullFolder = fullfile(resultsFolder,'01_concentration_xz_full_0_to_1');
yzFullFolder = fullfile(resultsFolder,'02_concentration_yz_full_0_to_1');

xzContrastFolder = fullfile( ...
    resultsFolder, ...
    ['03_concentration_xz_contrast_' contrastTag '_to_1_thesis']);

yzContrastFolder = fullfile( ...
    resultsFolder, ...
    ['04_concentration_yz_contrast_' contrastTag '_to_1_thesis']);

xzNormalisedFolder = fullfile( ...
    resultsFolder, ...
    '05_concentration_xz_per_time_normalised_0_to_1_thesis');

yzNormalisedFolder = fullfile( ...
    resultsFolder, ...
    '06_concentration_yz_per_time_normalised_0_to_1_thesis');

% Velocity folders.
xzStreamFolder = fullfile( ...
    resultsFolder, ...
    '07_velocity_xz_streamlines_clean_thesis');

yzStreamFolder = fullfile( ...
    resultsFolder, ...
    '08_velocity_yz_streamlines_clean_thesis');

xzVelocityFolder = fullfile( ...
    resultsFolder, ...
    '09_velocity_xz_magnitude_streamlines');

yzVelocityFolder = fullfile( ...
    resultsFolder, ...
    '10_velocity_yz_magnitude_streamlines');

% Plan-view folders.
xyFullFolder = fullfile( ...
    resultsFolder, ...
    '11_final_xy_plan_full_0_to_1');

xyContrastFolder = fullfile( ...
    resultsFolder, ...
    ['12_final_xy_plan_contrast_' contrastTag '_to_1_thesis']);

xyNormalisedFolder = fullfile( ...
    resultsFolder, ...
    '13_final_xy_plan_per_time_normalised_thesis');

foldersToCreate = { ...
    xzFullFolder, ...
    yzFullFolder, ...
    xzContrastFolder, ...
    yzContrastFolder, ...
    xzNormalisedFolder, ...
    yzNormalisedFolder, ...
    xzStreamFolder, ...
    yzStreamFolder, ...
    xzVelocityFolder, ...
    yzVelocityFolder, ...
    xyFullFolder, ...
    xyContrastFolder, ...
    xyNormalisedFolder};

for j = 1:numel(foldersToCreate)
    if ~exist(foldersToCreate{j},'dir')
        mkdir(foldersToCreate{j})
    end
end


%% ================================================================
%  DISCOVER + STITCH ALL RESTART SEGMENTS


fprintf('\n')
fprintf('================================================\n')
fprintf('DISCOVERING RECTANGULAR 3D FEniCS OUTPUT\n')
fprintf('================================================\n\n')

cSeries = discoverXDMFSeries( ...
    dataRoot, ...
    'c_hdiv_v2');

if isempty(cSeries)
    error([ ...
        'No c_hdiv_v2.xdmf files were found under:\n%s\n\n' ...
        'Run this script from the overall result root or a segment folder.'], ...
        dataRoot)
end

uSeries = discoverXDMFSeries( ...
    dataRoot, ...
    'u_hdiv_v2');

times = [cSeries.time]';
nTimes = numel(times);

velocityAvailable = ~isempty(uSeries);

fprintf('Concentration fields after stitching : %d\n',nTimes)
fprintf('First concentration time             : %.6f s\n',times(1))
fprintf('Last concentration time              : %.6f s\n',times(end))
fprintf('Velocity series available            : %d\n',velocityAvailable)
fprintf('Contrast display                     : %.3f to 1.000\n\n', ...
    contrastLower)

if velocityAvailable
    fprintf('Velocity fields after stitching      : %d\n',numel(uSeries))
    fprintf('Velocity time range                  : %.6f to %.6f s\n\n', ...
        uSeries(1).time, ...
        uSeries(end).time)
end


%% ================================================================
%  BUILD REQUESTED TIMES


sliceRequestedTimes = makeRequestedTimes( ...
    times(end), ...
    sliceTimeSpacing);

profileRequestedTimes = makeRequestedTimes( ...
    times(end), ...
    profileTimeSpacing);

streamlineRequestedTimes = makeRequestedTimes( ...
    times(end), ...
    streamlineTimeSpacing);

[sliceIndices,sliceTimes] = nearestSavedTimes( ...
    times, ...
    sliceRequestedTimes);

[profileIndices,profileTimes] = nearestSavedTimes( ...
    times, ...
    profileRequestedTimes);

[streamlineIndices,streamlineTimes] = nearestSavedTimes( ...
    times, ...
    streamlineRequestedTimes);

fprintf('Thesis concentration slice times:\n')
fprintf('  %.3f',sliceTimes)
fprintf('\n\n')

fprintf('Thesis profile times:\n')
fprintf('  %.3f',profileTimes)
fprintf('\n\n')

if velocityAvailable
    fprintf('Velocity streamline times:\n')
    fprintf('  %.3f',streamlineTimes)
    fprintf('\n\n')
end


%% ================================================================
%  READ REFERENCE CONCENTRATION MESH


referenceH5 = cSeries(1).h5File;

geometry = readGeometry(referenceH5);

topology = h5read( ...
    referenceH5, ...
    '/Mesh/0/mesh/topology');

if size(topology,2) ~= 4 && size(topology,1) == 4
    topology = topology';
end

if size(topology,2) ~= 4
    error('Unexpected tetrahedral topology dimensions in concentration H5.')
end

% FEniCS topology is zero-based.
tetra = double(topology) + 1;

nVertices = size(geometry,1);
nCells = size(tetra,1);

xMeshMin = min(geometry(:,1));
xMeshMax = max(geometry(:,1));
yMeshMin = min(geometry(:,2));
yMeshMax = max(geometry(:,2));
zMeshMin = min(geometry(:,3));
zMeshMax = max(geometry(:,3));

fprintf('Reference mesh:\n')
fprintf('  vertices = %d\n',nVertices)
fprintf('  cells    = %d\n',nCells)
fprintf('  x range  = %.6f to %.6f m\n',xMeshMin,xMeshMax)
fprintf('  y range  = %.6f to %.6f m\n',yMeshMin,yMeshMax)
fprintf('  z range  = %.6f to %.6f m\n\n',zMeshMin,zMeshMax)


%% ================================================================
%  GEOMETRY SANITY CHECK


geometryTolerance = 1.0e-8;

geometryIsCorrect = ...
    abs(xMeshMin-xMinExpected) < geometryTolerance ...
    && ...
    abs(xMeshMax-xMaxExpected) < geometryTolerance ...
    && ...
    abs(yMeshMin-yMinExpected) < geometryTolerance ...
    && ...
    abs(yMeshMax-yMaxExpected) < geometryTolerance ...
    && ...
    abs(zMeshMin-zMinExpected) < geometryTolerance ...
    && ...
    abs(zMeshMax-zMaxExpected) < geometryTolerance;

if ~geometryIsCorrect
    fprintf('\n')
    fprintf('================================================\n')
    fprintf('WRONG 3D GEOMETRY DETECTED\n')
    fprintf('================================================\n\n')
    fprintf('Expected:\n')
    fprintf('  x = -0.300 to +0.300 m\n')
    fprintf('  y = -0.150 to +0.150 m\n')
    fprintf('  z =  0.000 to +0.200 m\n\n')
    fprintf('Loaded:\n')
    fprintf('  x = %.6f to %.6f m\n',xMeshMin,xMeshMax)
    fprintf('  y = %.6f to %.6f m\n',yMeshMin,yMeshMax)
    fprintf('  z = %.6f to %.6f m\n',zMeshMin,zMeshMax)

    error('This is not the corrected rectangular experimental geometry.')
end

fprintf('RECTANGULAR GEOMETRY CHECK PASSED.\n\n')


%% ================================================================
%  TETRAHEDRON CENTRES + VOLUMES


P1 = geometry(tetra(:,1),:);
P2 = geometry(tetra(:,2),:);
P3 = geometry(tetra(:,3),:);
P4 = geometry(tetra(:,4),:);

cellCentre = (P1 + P2 + P3 + P4) / 4;

v21 = P2-P1;
v31 = P3-P1;
v41 = P4-P1;

cellVolume = abs( ...
    dot(v21,cross(v31,v41,2),2)) ...
    / 6;

xCell = cellCentre(:,1);
yCell = cellCentre(:,2);
zCell = cellCentre(:,3);

meshVolume = sum(cellVolume);
exactVolume = L*W*H;

fprintf('Tank-volume check:\n')
fprintf('  mesh volume  = %.12e m^3\n',meshVolume)
fprintf('  exact volume = %.12e m^3\n',exactVolume)
fprintf('  error        = %.6e %%\n\n', ...
    100*abs(meshVolume-exactVolume)/exactVolume)


%% ================================================================
%  VERTICAL BINS FOR HORIZONTAL AVERAGING


zEdges = linspace(0,H,nZBins+1);

zAverage = 0.5*( ...
    zEdges(1:end-1) ...
    + ...
    zEdges(2:end));

zAverage = zAverage(:);

cellLayer = discretize(zCell,zEdges);

validCells = ...
    ~isnan(cellLayer) ...
    & ...
    cellLayer >= 1 ...
    & ...
    cellLayer <= nZBins;

layerVolume = accumarray( ...
    cellLayer(validCells), ...
    cellVolume(validCells), ...
    [nZBins 1], ...
    @sum, ...
    0);

centralMask = ...
    abs(xCell) <= centralHalfWidthX ...
    & ...
    abs(yCell) <= centralHalfWidthY;

validCentral = validCells & centralMask;

centralLayerVolume = accumarray( ...
    cellLayer(validCentral), ...
    cellVolume(validCentral), ...
    [nZBins 1], ...
    @sum, ...
    0);

if any(layerVolume == 0)
    error([ ...
        'At least one full-tank z-bin has no cell centres. ' ...
        'Reduce nZBins.'])
end

if any(centralLayerVolume == 0)
    warning([ ...
        'Some central-region z-bins contain no cells. ' ...
        'Central mean will contain NaNs there.'])
end


%% ================================================================
%  VISUAL GRIDS


xXZ = linspace(-L/2,L/2,nxXZ);
zXZ = linspace(0,H,nzXZ);
[XXZ,ZXZ] = meshgrid(xXZ,zXZ);

yYZ = linspace(-W/2,W/2,nyYZ);
zYZ = linspace(0,H,nzYZ);
[YYZ,ZYZ] = meshgrid(yYZ,zYZ);

xXY = linspace(-L/2,L/2,nxXY);
yXY = linspace(-W/2,W/2,nyXY);
[XXY,YXY] = meshgrid(xXY,yXY);


%% ================================================================
%  STORAGE


cBarAll = nan(nZBins,nTimes);
cBarCentral = nan(nZBins,nTimes);

freshVolume = nan(nTimes,1);
cMinimum = nan(nTimes,1);
cMaximum = nan(nTimes,1);


%% ================================================================
%  PROCESS ALL CONCENTRATION FIELDS


fprintf('Processing stitched concentration series...\n\n')

for k = 1:nTimes

    cCell = readScalarDataset( ...
        cSeries(k).h5File, ...
        cSeries(k).datasetPath);

    if numel(cCell) ~= nCells
        error([ ...
            'Field at t = %.6f s has %d values, ' ...
            'but reference mesh has %d tetrahedra.'], ...
            times(k), ...
            numel(cCell), ...
            nCells)
    end

    cMinimum(k) = min(cCell);
    cMaximum(k) = max(cCell);


    % Full-tank volume-weighted horizontal mean.


    weightedFull = accumarray( ...
        cellLayer(validCells), ...
        cCell(validCells).*cellVolume(validCells), ...
        [nZBins 1], ...
        @sum, ...
        0);

    cBarAll(:,k) = ...
        weightedFull ...
        ./ ...
        layerVolume;


    % Central 6 cm x 6 cm volume-weighted mean.


    weightedCentral = accumarray( ...
        cellLayer(validCentral), ...
        cCell(validCentral).*cellVolume(validCentral), ...
        [nZBins 1], ...
        @sum, ...
        0);

    goodCentralBins = centralLayerVolume > 0;

    cBarCentral(goodCentralBins,k) = ...
        weightedCentral(goodCentralBins) ...
        ./ ...
        centralLayerVolume(goodCentralBins);


    % Total fresh-water volume.


    freshVolume(k) = sum( ...
        (1-cCell) ...
        .* ...
        cellVolume);


    % Thesis concentration slices.


    if any(sliceIndices == k)

        fprintf('  concentration slices at t = %.3f s\n',times(k))

        timeTag = timeToTag(times(k));


        % x-z concentration slice


        xzMask = abs(yCell) <= sliceHalfThicknessXZ;

        F_xz = scatteredInterpolant( ...
            xCell(xzMask), ...
            zCell(xzMask), ...
            cCell(xzMask), ...
            'linear', ...
            'nearest');

        Cxz = F_xz(XXZ,ZXZ);

        % Plotting only: remove tiny solver overshoots.
        Cxz = max(0,min(1,Cxz));

        exportScalarSlice( ...
            xXZ, ...
            zXZ, ...
            Cxz, ...
            [-L/2 L/2], ...
            [0 H], ...
            [0 1], ...
            [1800 600], ...
            xzFullFolder, ...
            ['xz_full_t_' timeTag 's.png'], ...
            pngResolution);

        exportScalarSlice( ...
            xXZ, ...
            zXZ, ...
            Cxz, ...
            [-L/2 L/2], ...
            [0 H], ...
            [contrastLower 1], ...
            [1800 600], ...
            xzContrastFolder, ...
            ['xz_contrast_' contrastTag '_t_' timeTag 's.png'], ...
            thesisPngResolution);

        CxzNormalised = normaliseConcentrationField(Cxz);

        exportScalarSlice( ...
            xXZ, ...
            zXZ, ...
            CxzNormalised, ...
            [-L/2 L/2], ...
            [0 H], ...
            [0 1], ...
            [1800 600], ...
            xzNormalisedFolder, ...
            ['xz_normalised_t_' timeTag 's.png'], ...
            thesisPngResolution);


        % y-z concentration slice


        yzMask = abs(xCell) <= sliceHalfThicknessYZ;

        F_yz = scatteredInterpolant( ...
            yCell(yzMask), ...
            zCell(yzMask), ...
            cCell(yzMask), ...
            'linear', ...
            'nearest');

        Cyz = F_yz(YYZ,ZYZ);
        Cyz = max(0,min(1,Cyz));

        exportScalarSlice( ...
            yYZ, ...
            zYZ, ...
            Cyz, ...
            [-W/2 W/2], ...
            [0 H], ...
            [0 1], ...
            [1200 800], ...
            yzFullFolder, ...
            ['yz_full_t_' timeTag 's.png'], ...
            pngResolution);

        exportScalarSlice( ...
            yYZ, ...
            zYZ, ...
            Cyz, ...
            [-W/2 W/2], ...
            [0 H], ...
            [contrastLower 1], ...
            [1200 800], ...
            yzContrastFolder, ...
            ['yz_contrast_' contrastTag '_t_' timeTag 's.png'], ...
            thesisPngResolution);

        CyzNormalised = normaliseConcentrationField(Cyz);

        exportScalarSlice( ...
            yYZ, ...
            zYZ, ...
            CyzNormalised, ...
            [-W/2 W/2], ...
            [0 H], ...
            [0 1], ...
            [1200 800], ...
            yzNormalisedFolder, ...
            ['yz_normalised_t_' timeTag 's.png'], ...
            thesisPngResolution);
    end

    if k == 1 || mod(k,10) == 0 || k == nTimes
        fprintf( ...
            '  processed %4d / %4d   t = %.3f s\n', ...
            k, ...
            nTimes, ...
            times(k))
    end
end

fprintf('\nAll concentration fields processed.\n\n')


%% ================================================================
%  VELOCITY STREAMLINES


if velocityAvailable

    fprintf('Processing velocity streamlines...\n\n')

    for j = 1:numel(streamlineTimes)

        tTarget = streamlineTimes(j);

        uIndex = nearestSeriesIndex( ...
            uSeries, ...
            tTarget, ...
            5.0e-8);

        if uIndex == 0
            warning( ...
                'No velocity field found at t = %.6f s. Skipping.', ...
                tTarget)
            continue
        end

        [uCoords,uValues] = readVectorDatasetWithGeometry( ...
            uSeries(uIndex).h5File, ...
            uSeries(uIndex).datasetPath);

        if size(uValues,2) < 3
            warning( ...
                'Velocity field at t = %.6f s is not 3-component. Skipping.', ...
                tTarget)
            continue
        end

        timeTag = timeToTag(tTarget);

        fprintf('  velocity streamlines at t = %.3f s\n',tTarget)


        % x-z streamlines, central slab around y = 0


        maskXZ = abs(uCoords(:,2)) <= velocitySliceHalfThickness;

        if nnz(maskXZ) >= 20

            Fux = scatteredInterpolant( ...
                uCoords(maskXZ,1), ...
                uCoords(maskXZ,3), ...
                uValues(maskXZ,1), ...
                'linear', ...
                'nearest');

            Fuz = scatteredInterpolant( ...
                uCoords(maskXZ,1), ...
                uCoords(maskXZ,3), ...
                uValues(maskXZ,3), ...
                'linear', ...
                'nearest');

            UxGrid = Fux(XXZ,ZXZ);
            UzGrid = Fuz(XXZ,ZXZ);

            speedXZ = sqrt(UxGrid.^2 + UzGrid.^2);

            exportCleanStreamlines( ...
                XXZ, ...
                ZXZ, ...
                UxGrid, ...
                UzGrid, ...
                [-L/2 L/2], ...
                [0 H], ...
                [1800 600], ...
                streamlineDensity, ...
                xzStreamFolder, ...
                ['xz_streamlines_t_' timeTag 's.png'], ...
                thesisPngResolution);

            exportVelocityMagnitudeStreamlines( ...
                xXZ, ...
                zXZ, ...
                XXZ, ...
                ZXZ, ...
                speedXZ, ...
                UxGrid, ...
                UzGrid, ...
                [-L/2 L/2], ...
                [0 H], ...
                [1800 600], ...
                streamlineDensity, ...
                velocityDisplayMax, ...
                xzVelocityFolder, ...
                ['xz_velocity_magnitude_streamlines_t_' timeTag 's.png'], ...
                pngResolution);
        else
            warning( ...
                'Too few velocity points for x-z streamlines at t = %.3f s.', ...
                tTarget)
        end


        % y-z streamlines, central slab around x = 0


        maskYZ = abs(uCoords(:,1)) <= velocitySliceHalfThickness;

        if nnz(maskYZ) >= 20

            Fuy = scatteredInterpolant( ...
                uCoords(maskYZ,2), ...
                uCoords(maskYZ,3), ...
                uValues(maskYZ,2), ...
                'linear', ...
                'nearest');

            FuzYZ = scatteredInterpolant( ...
                uCoords(maskYZ,2), ...
                uCoords(maskYZ,3), ...
                uValues(maskYZ,3), ...
                'linear', ...
                'nearest');

            UyGrid = Fuy(YYZ,ZYZ);
            UzGridYZ = FuzYZ(YYZ,ZYZ);

            speedYZ = sqrt(UyGrid.^2 + UzGridYZ.^2);

            exportCleanStreamlines( ...
                YYZ, ...
                ZYZ, ...
                UyGrid, ...
                UzGridYZ, ...
                [-W/2 W/2], ...
                [0 H], ...
                [1200 800], ...
                streamlineDensity, ...
                yzStreamFolder, ...
                ['yz_streamlines_t_' timeTag 's.png'], ...
                thesisPngResolution);

            exportVelocityMagnitudeStreamlines( ...
                yYZ, ...
                zYZ, ...
                YYZ, ...
                ZYZ, ...
                speedYZ, ...
                UyGrid, ...
                UzGridYZ, ...
                [-W/2 W/2], ...
                [0 H], ...
                [1200 800], ...
                streamlineDensity, ...
                velocityDisplayMax, ...
                yzVelocityFolder, ...
                ['yz_velocity_magnitude_streamlines_t_' timeTag 's.png'], ...
                pngResolution);
        else
            warning( ...
                'Too few velocity points for y-z streamlines at t = %.3f s.', ...
                tTarget)
        end
    end

    fprintf('\nVelocity streamline processing complete.\n\n')
else
    warning([ ...
        'No u_hdiv_v2.xdmf files were found. ' ...
        'Concentration processing will continue without velocity figures.'])
end


%% ================================================================
%  FINAL-TIME x-y PLAN SLICES


cFinal = readScalarDataset( ...
    cSeries(end).h5File, ...
    cSeries(end).datasetPath);

for j = 1:numel(planZFractions)

    zFraction = planZFractions(j);
    zTarget = zFraction*H;

    xyMask = ...
        abs(zCell-zTarget) ...
        <= ...
        sliceHalfThicknessXY;

    if nnz(xyMask) < 50
        warning( ...
            'Too few cells for x-y slice at z/H = %.2f.', ...
            zFraction)
        continue
    end

    F_xy = scatteredInterpolant( ...
        xCell(xyMask), ...
        yCell(xyMask), ...
        cFinal(xyMask), ...
        'linear', ...
        'nearest');

    Cxy = F_xy(XXY,YXY);
    Cxy = max(0,min(1,Cxy));

    zTag = strrep(sprintf('%0.2f',zFraction),'.','p');

    exportScalarSlice( ...
        xXY, ...
        yXY, ...
        Cxy, ...
        [-L/2 L/2], ...
        [-W/2 W/2], ...
        [0 1], ...
        [1600 800], ...
        xyFullFolder, ...
        ['xy_final_full_zOverH_' zTag '.png'], ...
        pngResolution);

    exportScalarSlice( ...
        xXY, ...
        yXY, ...
        Cxy, ...
        [-L/2 L/2], ...
        [-W/2 W/2], ...
        [contrastLower 1], ...
        [1600 800], ...
        xyContrastFolder, ...
        ['xy_final_contrast_' contrastTag '_zOverH_' zTag '.png'], ...
        thesisPngResolution);

    CxyNormalised = normaliseConcentrationField(Cxy);

    exportScalarSlice( ...
        xXY, ...
        yXY, ...
        CxyNormalised, ...
        [-L/2 L/2], ...
        [-W/2 W/2], ...
        [0 1], ...
        [1600 800], ...
        xyNormalisedFolder, ...
        ['xy_final_normalised_zOverH_' zTag '.png'], ...
        thesisPngResolution);
end


%% ================================================================
%  DERIVED HORIZONTAL-AVERAGE FIELDS


freshMean = 1-cBarAll;

% Physical roundoff can create O(1e-8) negative values because c can
% slightly exceed one.  Clip ONLY these post-processing diagnostics.
freshMeanForPlots = max(0,freshMean);


% Global normalisation
%
% One scale for the entire time history.
% Retains amplitude changes between times.


maxFreshMeanGlobal = max( ...
    freshMeanForPlots(:), ...
    [], ...
    'omitnan');

if maxFreshMeanGlobal > 0
    freshMeanNormalisedGlobal = ...
        freshMeanForPlots ...
        / ...
        maxFreshMeanGlobal;
else
    freshMeanNormalisedGlobal = zeros(size(freshMeanForPlots));
end


% Per-time normalisation
%
% Each vertical profile is separately scaled to [0,1].
% This removes amplitude information and isolates the evolving vertical
% SHAPE of the fresh-water / stratification layer.


freshMeanNormalisedEachTime = nan(size(freshMeanForPlots));

for k = 1:nTimes

    column = freshMeanForPlots(:,k);
    columnMax = max(column,[],'omitnan');

    if isfinite(columnMax) && columnMax > 0
        freshMeanNormalisedEachTime(:,k) = column/columnMax;
    else
        freshMeanNormalisedEachTime(:,k) = zeros(size(column));
    end
end


%% ================================================================
%  SELECTED FULL-TANK PROFILES


cBarSelected = cBarAll(:,profileIndices);

freshSelected = max(0,1-cBarSelected);

freshSelectedNormalised = nan(size(freshSelected));

for j = 1:size(freshSelected,2)

    thisMax = max(freshSelected(:,j),[],'omitnan');

    if isfinite(thisMax) && thisMax > 0
        freshSelectedNormalised(:,j) = ...
            freshSelected(:,j)/thisMax;
    else
        freshSelectedNormalised(:,j) = ...
            zeros(size(freshSelected(:,j)));
    end
end

nProfileSelected = numel(profileTimes);

% Pale pink -> dark red, matching the other numerical-model figures.
profileColors = [ ...
    ones(nProfileSelected,1), ...
    linspace(0.72,0.00,nProfileSelected)', ...
    linspace(0.72,0.00,nProfileSelected)' ...
    ];

% Find a sensible absolute concentration x limit.
allSelected = cBarSelected(:);
allSelected = allSelected(isfinite(allSelected));

if isempty(allSelected)
    xLower = 0.99;
else
    cMinSelected = min(allSelected);
    deviation = max(1-cMinSelected,1e-6);
    xLower = max(0,cMinSelected-0.10*deviation);
end


%% ================================================================
%  CLEAN THESIS-READY ABSOLUTE MEAN PROFILES


fig = figure( ...
    'Color','w', ...
    'Visible','off', ...
    'Units','pixels', ...
    'Position',[100 100 900 1200]);

ax = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',[0 0 1 1]);

hold(ax,'on')

for j = 1:nProfileSelected
    plot( ...
        ax, ...
        cBarSelected(:,j), ...
        zAverage/H, ...
        'LineWidth',4.0, ...
        'Color',profileColors(j,:));
end

xlim(ax,[xLower 1]);
ylim(ax,[0 1]);

axis(ax,'off');

exportgraphics( ...
    ax, ...
    fullfile( ...
        resultsFolder, ...
        'THESIS_full_tank_average_profiles_clean.png'), ...
    'Resolution',600, ...
    'BackgroundColor','white');

close(fig)


%% ================================================================
%  LABELLED ABSOLUTE MEAN PROFILES


fig = figure( ...
    'Color','w', ...
    'Visible','off', ...
    'Units','pixels', ...
    'Position',[100 100 800 1000]);

ax = axes('Parent',fig);
hold(ax,'on')

for j = 1:nProfileSelected
    plot( ...
        ax, ...
        cBarSelected(:,j), ...
        zAverage/H, ...
        'LineWidth',2.5, ...
        'Color',profileColors(j,:));
end

xlabel(ax,'$\overline{c}$','Interpreter','latex');
ylabel(ax,'$z/H$','Interpreter','latex');

xlim(ax,[xLower 1]);
ylim(ax,[0 1]);

set(ax, ...
    'FontSize',14, ...
    'LineWidth',1.2, ...
    'Box','on');

exportgraphics( ...
    fig, ...
    fullfile( ...
        resultsFolder, ...
        'full_tank_average_profiles_labelled.png'), ...
    'Resolution',300);

close(fig)


%% ================================================================
%  CLEAN THESIS-READY NORMALISED MEAN PROFILES
%
%     phi(z,t) = (1-cbar) / max_z(1-cbar)
%
%  Each curve therefore spans 0 to 1.  This is the useful figure for
%  comparing the SHAPE and downward growth of the weak stratified layer
%  without the absolute concentration amplitude dominating the plot.


fig = figure( ...
    'Color','w', ...
    'Visible','off', ...
    'Units','pixels', ...
    'Position',[100 100 900 1200]);

ax = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',[0 0 1 1]);

hold(ax,'on')

for j = 1:nProfileSelected
    plot( ...
        ax, ...
        freshSelectedNormalised(:,j), ...
        zAverage/H, ...
        'LineWidth',4.0, ...
        'Color',profileColors(j,:));
end

xlim(ax,[0 1]);
ylim(ax,[0 1]);
axis(ax,'off');

exportgraphics( ...
    ax, ...
    fullfile( ...
        resultsFolder, ...
        'THESIS_normalised_fresh_profiles_clean.png'), ...
    'Resolution',600, ...
    'BackgroundColor','white');

close(fig)


%% ================================================================
%  LABELLED NORMALISED MEAN PROFILES


fig = figure( ...
    'Color','w', ...
    'Visible','off', ...
    'Units','pixels', ...
    'Position',[100 100 800 1000]);

ax = axes('Parent',fig);
hold(ax,'on')

for j = 1:nProfileSelected
    plot( ...
        ax, ...
        freshSelectedNormalised(:,j), ...
        zAverage/H, ...
        'LineWidth',2.5, ...
        'Color',profileColors(j,:));
end

xlabel( ...
    ax, ...
    '$\phi=(1-\overline{c})/\max_z(1-\overline{c})$', ...
    'Interpreter','latex');

ylabel(ax,'$z/H$','Interpreter','latex');

xlim(ax,[0 1]);
ylim(ax,[0 1]);

set(ax, ...
    'FontSize',14, ...
    'LineWidth',1.2, ...
    'Box','on');

exportgraphics( ...
    fig, ...
    fullfile( ...
        resultsFolder, ...
        'normalised_fresh_profiles_labelled.png'), ...
    'Resolution',300);

close(fig)


%% ================================================================
%  CENTRAL 6 cm x 6 cm MEAN PROFILES


centralSelected = cBarCentral(:,profileIndices);

fig = figure( ...
    'Color','w', ...
    'Visible','off', ...
    'Units','pixels', ...
    'Position',[100 100 800 1000]);

ax = axes('Parent',fig);
hold(ax,'on')

for j = 1:nProfileSelected
    plot( ...
        ax, ...
        centralSelected(:,j), ...
        zAverage/H, ...
        'LineWidth',2.5, ...
        'Color',profileColors(j,:));
end

xlabel( ...
    ax, ...
    '$\overline{c}_{\mathrm{centre}}$', ...
    'Interpreter','latex');

ylabel(ax,'$z/H$','Interpreter','latex');

xlim(ax,[0 1]);
ylim(ax,[0 1]);

set(ax, ...
    'FontSize',14, ...
    'LineWidth',1.2, ...
    'Box','on');

exportgraphics( ...
    fig, ...
    fullfile( ...
        resultsFolder, ...
        'central_region_average_profiles.png'), ...
    'Resolution',300);

close(fig)


%% ================================================================
%  TIME-HEIGHT MAP: ABSOLUTE FULL-TANK MEAN CONCENTRATION


exportTimeHeightMap( ...
    times, ...
    zAverage/H, ...
    cBarAll, ...
    [0 1], ...
    true, ...
    '$\overline{c}$', ...
    fullfile( ...
        resultsFolder, ...
        'full_tank_average_time_height_full_range.png'));


%% ================================================================
%  TIME-HEIGHT MAP: HIGH-CONTRAST FULL-TANK MEAN CONCENTRATION
%
%  This is likely the most useful absolute stratification map because
%  the whole-tank mean remains close to one at early/intermediate times.


exportTimeHeightMap( ...
    times, ...
    zAverage/H, ...
    cBarAll, ...
    [contrastLower 1], ...
    true, ...
    '$\overline{c}$', ...
    fullfile( ...
        resultsFolder, ...
        ['THESIS_full_tank_average_time_height_contrast_' ...
         contrastTag '.png']));


%% ================================================================
%  TIME-HEIGHT MAP: MEAN FRESH-WATER FRACTION


exportTimeHeightMap( ...
    times, ...
    zAverage/H, ...
    freshMeanForPlots, ...
    [], ...
    false, ...
    '$1-\overline{c}$', ...
    fullfile( ...
        resultsFolder, ...
        'full_tank_mean_fresh_fraction_time_height.png'));


%% ================================================================
%  TIME-HEIGHT MAP: GLOBALLY NORMALISED FRESH-WATER DEFICIT
%
%  One normalisation over all z and t.
%  Relative amplitude between times is retained.


exportTimeHeightMap( ...
    times, ...
    zAverage/H, ...
    freshMeanNormalisedGlobal, ...
    [0 1], ...
    false, ...
    'globally normalised $1-\overline{c}$', ...
    fullfile( ...
        resultsFolder, ...
        'full_tank_global_normalised_fresh_deficit_time_height.png'));


%% ================================================================
%  TIME-HEIGHT MAP: PER-TIME NORMALISED FRESH-WATER DEFICIT
%
%  Every time column is independently scaled to [0,1].
%  This deliberately removes amplitude information and makes the
%  evolution of the vertical layer shape much easier to see.


exportTimeHeightMap( ...
    times, ...
    zAverage/H, ...
    freshMeanNormalisedEachTime, ...
    [0 1], ...
    false, ...
    'per-time normalised $1-\overline{c}$', ...
    fullfile( ...
        resultsFolder, ...
        'THESIS_per_time_normalised_fresh_deficit_time_height.png'));


%% ================================================================
%  FRESH-WATER VOLUME VERSUS TIME


fig = figure( ...
    'Color','w', ...
    'Visible','off', ...
    'Units','pixels', ...
    'Position',[100 100 1000 650]);

ax = axes('Parent',fig);

plot( ...
    ax, ...
    times, ...
    freshVolume, ...
    'k-', ...
    'LineWidth',2.2);

xlabel(ax,'$t$ (s)','Interpreter','latex');

ylabel( ...
    ax, ...
    '$V_{\mathrm{fresh}}$ (m$^3$)', ...
    'Interpreter','latex');

set(ax, ...
    'FontSize',14, ...
    'LineWidth',1.2, ...
    'Box','on');

exportgraphics( ...
    fig, ...
    fullfile( ...
        resultsFolder, ...
        'fresh_water_volume_vs_time.png'), ...
    'Resolution',300);

close(fig)


%% ================================================================
%  SAVE MAT DATA


save( ...
    fullfile( ...
        resultsFolder, ...
        'rectangular_3D_postprocessing_data.mat'), ...
    'times', ...
    'zAverage', ...
    'zEdges', ...
    'cBarAll', ...
    'cBarCentral', ...
    'freshMean', ...
    'freshMeanForPlots', ...
    'freshMeanNormalisedGlobal', ...
    'freshMeanNormalisedEachTime', ...
    'freshVolume', ...
    'cMinimum', ...
    'cMaximum', ...
    'layerVolume', ...
    'L', ...
    'W', ...
    'H', ...
    'sliceTimes', ...
    'profileTimes', ...
    'streamlineTimes', ...
    'contrastLower');


%% ================================================================
%  SAVE LONG-FORM CSV


nRows = nTimes*nZBins;

timeColumn = zeros(nRows,1);
zColumn = zeros(nRows,1);
cMeanColumn = zeros(nRows,1);
centralMeanColumn = zeros(nRows,1);
freshMeanColumn = zeros(nRows,1);
freshGlobalNormColumn = zeros(nRows,1);
freshTimeNormColumn = zeros(nRows,1);

rowStart = 1;

for k = 1:nTimes

    rows = rowStart:(rowStart+nZBins-1);

    timeColumn(rows) = times(k);
    zColumn(rows) = zAverage/H;
    cMeanColumn(rows) = cBarAll(:,k);
    centralMeanColumn(rows) = cBarCentral(:,k);
    freshMeanColumn(rows) = freshMeanForPlots(:,k);
    freshGlobalNormColumn(rows) = freshMeanNormalisedGlobal(:,k);
    freshTimeNormColumn(rows) = freshMeanNormalisedEachTime(:,k);

    rowStart = rowStart+nZBins;
end

profileTable = table( ...
    timeColumn, ...
    zColumn, ...
    cMeanColumn, ...
    centralMeanColumn, ...
    freshMeanColumn, ...
    freshGlobalNormColumn, ...
    freshTimeNormColumn, ...
    'VariableNames', ...
    { ...
    'time_s', ...
    'z_over_H', ...
    'c_mean_full_tank', ...
    'c_mean_central_region', ...
    'fresh_fraction_mean', ...
    'fresh_fraction_global_normalised', ...
    'fresh_fraction_per_time_normalised' ...
    });

writetable( ...
    profileTable, ...
    fullfile( ...
        resultsFolder, ...
        'rectangular_3D_horizontal_average_all_times.csv'));


%% ================================================================
%  SAVE GLOBAL TIME-SERIES CSV


timeTable = table( ...
    times, ...
    freshVolume, ...
    cMinimum, ...
    cMaximum, ...
    'VariableNames', ...
    { ...
    'time_s', ...
    'fresh_volume_m3', ...
    'c_min', ...
    'c_max' ...
    });

writetable( ...
    timeTable, ...
    fullfile( ...
        resultsFolder, ...
        'rectangular_3D_global_time_series.csv'));


%% ================================================================
%  SAVE THESIS PROFILE TIMES CSV


profileTimeTable = table( ...
    profileTimes(:), ...
    'VariableNames',{'profile_time_s'});

writetable( ...
    profileTimeTable, ...
    fullfile( ...
        resultsFolder, ...
        'thesis_profile_times.csv'));


%% ================================================================
%  SUMMARY


fprintf('\n')
fprintf('================================================\n')
fprintf('RECTANGULAR 3D THESIS POST-PROCESSING COMPLETE\n')
fprintf('================================================\n\n')

fprintf('Domain processed:\n')
fprintf('  L = %.3f m\n',L)
fprintf('  W = %.3f m\n',W)
fprintf('  H = %.3f m\n\n',H)

fprintf('Processed %d stitched concentration fields.\n',nTimes)
fprintf('Final saved time = %.3f s\n',times(end))
fprintf('Vertical bins = %d\n',nZBins)
fprintf('Final fresh-water volume = %.8e m^3\n',freshVolume(end))

fprintf('Overall concentration range = %.10g to %.10g\n', ...
    min(cMinimum), ...
    max(cMaximum))

fprintf('\nThesis concentration contrast = %.2f to 1\n',contrastLower)
fprintf('Velocity streamlines available = %d\n',velocityAvailable)

fprintf('\nResults saved in:\n%s\n',resultsFolder)

fprintf('\nMain thesis-ready files include:\n')
fprintf('  THESIS_full_tank_average_profiles_clean.png\n')
fprintf('  THESIS_normalised_fresh_profiles_clean.png\n')
fprintf('  THESIS_full_tank_average_time_height_contrast_%s.png\n', ...
    contrastTag)
fprintf('  THESIS_per_time_normalised_fresh_deficit_time_height.png\n')

fprintf('\nThesis concentration folders:\n')
fprintf('  %s\n',xzContrastFolder)
fprintf('  %s\n',yzContrastFolder)
fprintf('  %s\n',xzNormalisedFolder)
fprintf('  %s\n',yzNormalisedFolder)

if velocityAvailable
    fprintf('\nVelocity streamline folders:\n')
    fprintf('  %s\n',xzStreamFolder)
    fprintf('  %s\n',yzStreamFolder)
end

fprintf('================================================\n\n')


%% ================================================================
%  LOCAL FUNCTIONS


function series = discoverXDMFSeries(rootFolder,baseName)

    files = dir(fullfile(rootFolder,'**',[baseName '.xdmf']));

    % Some MATLAB versions do not include the root itself in ** searches.
    directFile = fullfile(rootFolder,[baseName '.xdmf']);

    if isfile(directFile)

        alreadyIncluded = false;

        for j = 1:numel(files)
            thisPath = fullfile(files(j).folder,files(j).name);

            if strcmp(thisPath,directFile)
                alreadyIncluded = true;
                break
            end
        end

        if ~alreadyIncluded
            extra = dir(directFile);
            files = [files; extra];
        end
    end

    series = struct( ...
        'time',{}, ...
        'xdmfFile',{}, ...
        'h5File',{}, ...
        'datasetPath',{});

    for iFile = 1:numel(files)

        xdmfPath = fullfile(files(iFile).folder,files(iFile).name);

        [folderPath,fileStem,~] = fileparts(xdmfPath);

        h5Path = fullfile(folderPath,[fileStem '.h5']);

        if ~isfile(h5Path)
            warning('Skipping %s because matching H5 file is absent.',xdmfPath)
            continue
        end

        xmlText = fileread(xdmfPath);

        timeTokens = regexp( ...
            xmlText, ...
            '<Time\s+Value="([^"]+)"', ...
            'tokens');

        if isempty(timeTokens)
            warning('No saved times found in %s. Skipping.',xdmfPath)
            continue
        end

        localTimes = zeros(numel(timeTokens),1);

        for k = 1:numel(timeTokens)
            localTimes(k) = str2double(timeTokens{k}{1});
        end

        datasetTokens = regexp( ...
            xmlText, ...
            '\.h5:(/VisualisationVector/[0-9]+)', ...
            'tokens');

        localPaths = cell(numel(localTimes),1);

        if numel(datasetTokens) >= numel(localTimes)

            allPaths = cell(numel(datasetTokens),1);

            for k = 1:numel(datasetTokens)
                allPaths{k} = datasetTokens{k}{1};
            end

            uniquePaths = unique(allPaths,'stable');

            if numel(uniquePaths) >= numel(localTimes)
                localPaths = uniquePaths(1:numel(localTimes));
            else
                for k = 1:numel(localTimes)
                    localPaths{k} = sprintf( ...
                        '/VisualisationVector/%d', ...
                        k-1);
                end
            end
        else
            for k = 1:numel(localTimes)
                localPaths{k} = sprintf( ...
                    '/VisualisationVector/%d', ...
                    k-1);
            end
        end

        for k = 1:numel(localTimes)

            entry.time = localTimes(k);
            entry.xdmfFile = xdmfPath;
            entry.h5File = h5Path;
            entry.datasetPath = localPaths{k};

            series(end+1) = entry; %#ok<AGROW>
        end
    end

    if isempty(series)
        return
    end

    [~,order] = sort([series.time]);
    series = series(order);

    % Restart segment boundaries contain the same physical time twice.
    % Keep the later file and remove duplicate times to 1e-9 s.
    keep = true(1,numel(series));

    for k = 2:numel(series)

        if abs(series(k).time-series(k-1).time) <= 1.0e-9
            keep(k-1) = false;
        end
    end

    series = series(keep);
end


function requestedTimes = makeRequestedTimes(finalTime,spacing)

    if finalTime <= 0
        requestedTimes = finalTime;
        return
    end

    requestedTimes = spacing:spacing:finalTime;

    if isempty(requestedTimes)
        requestedTimes = finalTime;
    elseif abs(requestedTimes(end)-finalTime) > 1.0e-9
        requestedTimes = [requestedTimes finalTime];
    end
end


function [indices,selectedTimes] = nearestSavedTimes(times,requestedTimes)

    indices = zeros(numel(requestedTimes),1);
    selectedTimes = zeros(numel(requestedTimes),1);

    for j = 1:numel(requestedTimes)
        [~,indices(j)] = min(abs(times-requestedTimes(j)));
        selectedTimes(j) = times(indices(j));
    end

    [indices,uniquePosition] = unique(indices,'stable');
    selectedTimes = selectedTimes(uniquePosition);
end


function geometry = readGeometry(h5File)

    geometry = h5read( ...
        h5File, ...
        '/Mesh/0/mesh/geometry');

    if size(geometry,2) ~= 3 && size(geometry,1) == 3
        geometry = geometry';
    end

    if size(geometry,2) ~= 3
        error('Unexpected geometry dimensions in %s.',h5File)
    end

    geometry = double(geometry);
end


function values = readScalarDataset(h5File,datasetPath)

    values = h5read(h5File,datasetPath);
    values = double(values(:));
end


function [coords,values] = readVectorDatasetWithGeometry(h5File,datasetPath)

    coords = readGeometry(h5File);
    raw = double(h5read(h5File,datasetPath));

    nPoints = size(coords,1);

    if ismatrix(raw) && size(raw,1) == nPoints && size(raw,2) == 3

        values = raw;

    elseif ismatrix(raw) && size(raw,2) == nPoints && size(raw,1) == 3

        values = raw';

    elseif numel(raw) == 3*nPoints

        % HDF5 vector data is commonly returned as 3 x N by MATLAB.
        values = reshape(raw,3,nPoints)';

    else

        error([ ...
            'Velocity dataset %s in %s has %d values, ' ...
            'but its XDMF geometry has %d points.'], ...
            datasetPath, ...
            h5File, ...
            numel(raw), ...
            nPoints)
    end
end


function index = nearestSeriesIndex(series,targetTime,tolerance)

    if isempty(series)
        index = 0;
        return
    end

    seriesTimes = [series.time];
    [difference,indexCandidate] = min(abs(seriesTimes-targetTime));

    if difference <= tolerance
        index = indexCandidate;
    else
        index = 0;
    end
end


function tag = timeToTag(timeValue)

    tag = strrep( ...
        sprintf('%06.2f',timeValue), ...
        '.', ...
        'p');
end


function Cnormalised = normaliseConcentrationField(C)

    finiteValues = C(isfinite(C));

    if isempty(finiteValues)
        Cnormalised = C;
        return
    end

    cLo = min(finiteValues);
    cHi = max(finiteValues);

    if cHi-cLo <= 1.0e-12
        Cnormalised = ones(size(C));
    else
        Cnormalised = (C-cLo)/(cHi-cLo);
    end

    Cnormalised = max(0,min(1,Cnormalised));
end


function exportScalarSlice( ...
    xVector, ...
    yVector, ...
    C, ...
    xLimits, ...
    yLimits, ...
    colourLimits, ...
    figureSize, ...
    outputFolder, ...
    filename, ...
    resolution)

    fig = figure( ...
        'Color','w', ...
        'Visible','off', ...
        'Units','pixels', ...
        'Position',[100 100 figureSize(1) figureSize(2)]);

    ax = axes( ...
        'Parent',fig, ...
        'Units','normalized', ...
        'Position',[0 0 1 1]);

    imagesc(ax,xVector,yVector,C);

    set(ax,'YDir','normal');

    clim(ax,colourLimits);

    colormap(ax,flipud(gray(256)));

    xlim(ax,xLimits);
    ylim(ax,yLimits);

    % Preserve the physical dimensions of the tank/slice.
    axis(ax,'image');
    axis(ax,'off');

    exportgraphics( ...
        ax, ...
        fullfile(outputFolder,filename), ...
        'Resolution',resolution, ...
        'BackgroundColor','white');

    close(fig)
end


function exportCleanStreamlines( ...
    X, ...
    Y, ...
    U, ...
    V, ...
    xLimits, ...
    yLimits, ...
    figureSize, ...
    density, ...
    outputFolder, ...
    filename, ...
    resolution)


    % THESIS STREAMLINE STYLE
    %
    % Match the other numerical-model figures:
    %   * white background
    %   * red streamlines
    %   * no axes
    %   * no colourbar/key
    %   * no enclosing box


    fig = figure( ...
        'Color','w', ...
        'Visible','off', ...
        'Units','pixels', ...
        'Position',[100 100 figureSize(1) figureSize(2)]);

    ax = axes( ...
        'Parent',fig, ...
        'Units','normalized', ...
        'Position',[0 0 1 1], ...
        'Color','w');

    hold(ax,'on')

    hStream = streamslice(ax,X,Y,U,V,density);

    if ~isempty(hStream)
        set(hStream, ...
            'Color',[0.75 0.00 0.00], ...
            'LineWidth',1.05);
    end

    xlim(ax,xLimits);
    ylim(ax,yLimits);

    % Preserve the true physical aspect ratio of the slice.
    axis(ax,'image');

    % Clean thesis style: no axes, ticks, labels, frame or key.
    axis(ax,'off');

    exportgraphics( ...
        ax, ...
        fullfile(outputFolder,filename), ...
        'Resolution',resolution, ...
        'BackgroundColor','white');

    close(fig)
end


function exportVelocityMagnitudeStreamlines( ...
    xVector, ...
    yVector, ...
    X, ...
    Y, ...
    speed, ...
    U, ...
    V, ...
    xLimits, ...
    yLimits, ...
    figureSize, ...
    density, ...
    velocityMax, ...
    outputFolder, ...
    filename, ...
    resolution)

    fig = figure( ...
        'Color','w', ...
        'Visible','off', ...
        'Units','pixels', ...
        'Position',[100 100 figureSize(1) figureSize(2)]);

    ax = axes('Parent',fig);

    imagesc(ax,xVector,yVector,speed);
    set(ax,'YDir','normal');

    hold(ax,'on')

    hStream = streamslice(ax,X,Y,U,V,density);

    if ~isempty(hStream)
        set(hStream, ...
            'Color','w', ...
            'LineWidth',0.65);
    end

    clim(ax,[0 velocityMax]);
    colormap(ax,parula(256));

    xlim(ax,xLimits);
    ylim(ax,yLimits);

    axis(ax,'image');

    xlabel(ax,'$x$ (m)','Interpreter','latex');
    ylabel(ax,'$z$ (m)','Interpreter','latex');

    cb = colorbar(ax);

    ylabel( ...
        cb, ...
        '$|\mathbf{u}|$ (m s$^{-1}$)', ...
        'Interpreter','latex');

    set(ax, ...
        'FontSize',13, ...
        'LineWidth',1.1, ...
        'Box','on');

    exportgraphics( ...
        fig, ...
        fullfile(outputFolder,filename), ...
        'Resolution',resolution, ...
        'BackgroundColor','white');

    close(fig)
end


function exportTimeHeightMap( ...
    times, ...
    zOverH, ...
    values, ...
    colourLimits, ...
    reverseGrey, ...
    colourbarLabel, ...
    outputFile)


    % TIME-HEIGHT DISPLAY
    %
    % IMPORTANT:
    % The quantitative values passed into this function are NOT
    % changed or re-saved.  For plotting only, the 4-mm vertical-bin
    % values are linearly interpolated onto a finer z/H grid.  This
    % avoids the artificial blocky striping produced by imagesc when
    % only 50 vertical bins are displayed at thesis resolution.


    times = times(:)';
    zOverH = zOverH(:);

    plotTimes = times;
    plotZ = zOverH;
    plotValues = values;

    % These values mirror the user settings at the top of the script.
    % Kept local so this function remains self-contained.
    useDisplayInterpolation = true;
    nZDisplay = 350;

    if ...
        useDisplayInterpolation ...
        && ...
        numel(times) >= 2 ...
        && ...
        numel(zOverH) >= 2

        plotZ = linspace( ...
            zOverH(1), ...
            zOverH(end), ...
            nZDisplay)';

        % Keep the original saved time coordinates.  Only the vertical
        % display direction is refined, so no additional temporal
        % behaviour is invented between saved FEniCS fields.
        plotTimes = times;

        plotValues = interp1( ...
            zOverH, ...
            values, ...
            plotZ, ...
            'linear');
    end

    fig = figure( ...
        'Color','w', ...
        'Visible','off', ...
        'Units','pixels', ...
        'Position',[100 100 1200 800]);

    ax = axes('Parent',fig);

    imagesc( ...
        ax, ...
        plotTimes, ...
        plotZ, ...
        plotValues);

    set(ax,'YDir','normal');

    xlim(ax,[times(1) times(end)]);
    ylim(ax,[0 1]);

    if ~isempty(colourLimits)
        clim(ax,colourLimits);
    end

    if reverseGrey
        colormap(ax,flipud(gray(256)));
    else
        colormap(ax,gray(256));
    end

    xlabel(ax,'$t$ (s)','Interpreter','latex');
    ylabel(ax,'$z/H$','Interpreter','latex');

    cb = colorbar(ax);

    ylabel( ...
        cb, ...
        colourbarLabel, ...
        'Interpreter','latex');

    set(ax, ...
        'FontSize',14, ...
        'LineWidth',1.2, ...
        'Box','on');

    exportgraphics( ...
        fig, ...
        outputFile, ...
        'Resolution',300, ...
        'BackgroundColor','white');

    close(fig)
end

