%% ================================================================
%  3D RECTANGULAR FEniCS CONCENTRATION POST-PROCESSING
%
%  EXPERIMENTAL DOMAIN:
%
%      L = 0.60 m   (x direction)
%      W = 0.30 m   (y direction)
%      H = 0.20 m   (z direction)
%
%  Coordinates used by the FEniCS model:
%
%      -0.30 <= x <= +0.30 m
%      -0.15 <= y <= +0.15 m
%       0.00 <= z <= +0.20 m
%
%  Concentration convention:
%
%      c = 0  fresh water
%      c = 1  salt water
%
%  Put this MATLAB file INSIDE the FEniCS output folder:
%
%      results_3D_rectangular_3s
%
%  beside:
%
%      c.xdmf
%      c.h5
%
%  OUTPUTS:
%
%    1. Correctly proportioned central x-z slices
%       (60 cm wide x 20 cm high)
%
%    2. Correctly proportioned central y-z slices
%       (30 cm wide x 20 cm high)
%
%    3. Final-time x-y plan views at several heights
%
%    4. Volume-weighted horizontal mean concentration:
%
%                sum_i c_i V_i
%      cbar(z) = ----------------
%                  sum_i V_i
%
%       using the ORIGINAL DG0 tetrahedral values.
%
%    5. Selected-time mean profiles
%
%    6. Time-height maps of:
%         cbar(z,t)
%         1-cbar(z,t)
%         globally normalised fresh-water deficit
%
%    7. Fresh-water volume versus time
%
%    8. MAT and CSV quantitative outputs.
%
%  IMPORTANT:
%
%  Interpolation is used ONLY for visual slice images.
%  All averages and fresh-water volumes use original DG0 cell values.
%


clear
close all
clc


%% ================================================================
%  USER SETTINGS


dataFolder = pwd;

xdmfFile = fullfile(dataFolder,'c_hdiv_v2.xdmf');
h5File   = fullfile(dataFolder,'c_hdiv_v2.h5');

% Correct experimental tank dimensions.
L = 0.600;
W = 0.300;
H = 0.200;

xMinExpected = -L/2;
xMaxExpected =  L/2;

yMinExpected = -W/2;
yMaxExpected =  W/2;

zMinExpected = 0.0;
zMaxExpected = H;


resultsFolder = fullfile( ...
    dataFolder, ...
    'MATLAB_3D_rectangular_postprocessing');


% Plot selected slices/profiles every 0.5 s.
% requestedTimes is constructed AFTER the XDMF times have been read,
% so it automatically continues to the final available saved field.
plotTimeSpacing = 0.5;


% Thesis-ready high-contrast concentration images.
%
% Normal images retain the full concentration range:
%       0 <= c <= 1
%
% Contrast images use:
%       0.97 <= c <= 1
%
% With the reversed greyscale this strongly reveals small fresh-water
% concentration deficits while retaining the same physical geometry.
contrastLower = 0.97;


% Full-tank horizontal averaging.
%
% 50 bins -> dz = 4 mm.
%
% This is intentionally not excessively fine because the bulk 3D mesh
% is much coarser than the locally refined plume/nozzle mesh.
nZBins = 50;


% Visual slice slabs.
%
% These are used ONLY to construct 2D pictures from cell-centred DG0
% data. They do NOT affect quantitative averaging.
sliceHalfThicknessXZ = 0.008;   % |y| <= 8 mm
sliceHalfThicknessYZ = 0.008;   % |x| <= 8 mm
sliceHalfThicknessXY = 0.006;   % around requested z plane


% Central region used for an OPTIONAL plume-focused average.
%
% This is useful because the whole 60 x 30 cm horizontal mean is
% dominated by ambient fluid during the first few seconds.
centralHalfWidthX = 0.030;      % +/- 3 cm
centralHalfWidthY = 0.030;      % +/- 3 cm


% Plot grids.
nxXZ = 900;
nzXZ = 300;

nyYZ = 600;
nzYZ = 400;

nxXY = 900;
nyXY = 450;


% Final-time horizontal plan views.
planZFractions = [ ...
    0.25 ...
    0.50 ...
    0.75 ...
    0.95];


% Output resolution.
pngResolution = 400;

% Higher resolution for clean thesis-ready contrast figures.
thesisPngResolution = 600;


%% ================================================================
%  CHECK INPUT FILES


if ~isfile(xdmfFile)

    error( ...
        ['Could not find c.xdmf.\n\n' ...
         'Put this script inside the FEniCS result folder:\n%s'], ...
        dataFolder)

end


if ~isfile(h5File)

    error( ...
        ['Could not find c.h5.\n\n' ...
         'Put this script inside the FEniCS result folder:\n%s'], ...
        dataFolder)

end


if ~exist(resultsFolder,'dir')
    mkdir(resultsFolder)
end


xzFolder = fullfile( ...
    resultsFolder, ...
    'central_xz_slices');

yzFolder = fullfile( ...
    resultsFolder, ...
    'central_yz_slices');

xyFolder = fullfile( ...
    resultsFolder, ...
    'final_xy_plan_slices');


% Separate clean thesis-ready contrast outputs.
xzContrastFolder = fullfile( ...
    resultsFolder, ...
    'central_xz_slices_contrast_0p97_thesis');

yzContrastFolder = fullfile( ...
    resultsFolder, ...
    'central_yz_slices_contrast_0p97_thesis');

xyContrastFolder = fullfile( ...
    resultsFolder, ...
    'final_xy_plan_slices_contrast_0p97_thesis');


if ~exist(xzFolder,'dir')
    mkdir(xzFolder)
end

if ~exist(yzFolder,'dir')
    mkdir(yzFolder)
end

if ~exist(xyFolder,'dir')
    mkdir(xyFolder)
end

if ~exist(xzContrastFolder,'dir')
    mkdir(xzContrastFolder)
end

if ~exist(yzContrastFolder,'dir')
    mkdir(yzContrastFolder)
end

if ~exist(xyContrastFolder,'dir')
    mkdir(xyContrastFolder)
end


%% ================================================================
%  READ TIMES + DATASET PATHS FROM XDMF


fprintf('\n')
fprintf('================================================\n')
fprintf('READING RECTANGULAR 3D FEniCS OUTPUT\n')
fprintf('================================================\n\n')


xmlText = fileread(xdmfFile);


timeTokens = regexp( ...
    xmlText, ...
    '<Time\s+Value="([^"]+)"', ...
    'tokens');


if isempty(timeTokens)
    error('No saved times were found in c.xdmf.')
end


nTimes = numel(timeTokens);

times = zeros(nTimes,1);


for k = 1:nTimes

    times(k) = str2double( ...
        timeTokens{k}{1});

end


% Automatically request plots every plotTimeSpacing seconds right
% through to the final saved FEniCS field.
requestedTimes = ...
    plotTimeSpacing:plotTimeSpacing:times(end);


% Always include the final saved field even when it does not lie
% exactly on the requested spacing.
if ...
    isempty(requestedTimes) ...
    || ...
    abs(requestedTimes(end)-times(end)) > 1e-9

    requestedTimes = [ ...
        requestedTimes ...
        times(end)];

end


% DOLFIN 2019.1 normally stores visualisation vectors as:
%
%     /VisualisationVector/0
%     /VisualisationVector/1
%     ...

datasetTokens = regexp( ...
    xmlText, ...
    '\.h5:(/VisualisationVector/[0-9]+)', ...
    'tokens');


datasetPaths = cell(nTimes,1);


if numel(datasetTokens) >= nTimes

    allPaths = cell( ...
        numel(datasetTokens), ...
        1);

    for k = 1:numel(datasetTokens)

        allPaths{k} = ...
            datasetTokens{k}{1};

    end


    uniquePaths = unique( ...
        allPaths, ...
        'stable');


    if numel(uniquePaths) >= nTimes

        datasetPaths = ...
            uniquePaths(1:nTimes);

    else

        for k = 1:nTimes

            datasetPaths{k} = sprintf( ...
                '/VisualisationVector/%d', ...
                k-1);

        end

    end

else

    for k = 1:nTimes

        datasetPaths{k} = sprintf( ...
            '/VisualisationVector/%d', ...
            k-1);

    end

end


fprintf('Saved fields : %d\n',nTimes)
fprintf('First time   : %.6f s\n',times(1))
fprintf('Last time    : %.6f s\n',times(end))
fprintf('Plot spacing : %.3f s\n',plotTimeSpacing)
fprintf('Contrast     : %.3f to 1.000\n\n',contrastLower)


%% ================================================================
%  READ TETRAHEDRAL MESH


geometry = h5read( ...
    h5File, ...
    '/Mesh/0/mesh/geometry');


topology = h5read( ...
    h5File, ...
    '/Mesh/0/mesh/topology');


% MATLAB/HDF5 ordering may transpose the arrays.

if ...
    size(geometry,2) ~= 3 ...
    && ...
    size(geometry,1) == 3

    geometry = geometry';

end


if size(geometry,2) ~= 3

    error( ...
        'Unexpected geometry dimensions in c.h5.')

end


if ...
    size(topology,2) ~= 4 ...
    && ...
    size(topology,1) == 4

    topology = topology';

end


if size(topology,2) ~= 4

    error( ...
        'Unexpected tetrahedral topology dimensions in c.h5.')

end


% FEniCS topology is zero-based.
tetra = double(topology) + 1;


nVertices = size(geometry,1);
nCells = size(tetra,1);


xMeshMin = min(geometry(:,1));
xMeshMax = max(geometry(:,1));

yMeshMin = min(geometry(:,2));
yMeshMax = max(geometry(:,2));

zMeshMin = min(geometry(:,3));
zMeshMax = max(geometry(:,3));


fprintf('Mesh:\n')
fprintf('  vertices = %d\n',nVertices)
fprintf('  cells    = %d\n',nCells)
fprintf('  x range  = %.6f to %.6f m\n', ...
    xMeshMin,xMeshMax)
fprintf('  y range  = %.6f to %.6f m\n', ...
    yMeshMin,yMeshMax)
fprintf('  z range  = %.6f to %.6f m\n\n', ...
    zMeshMin,zMeshMax)


%% ================================================================
%  GEOMETRY SANITY CHECK
%
%  This deliberately rejects the OLD cylindrical 3D output.


geometryTolerance = 1.0e-8;


geometryIsCorrect = ...
    abs(xMeshMin-xMinExpected) < geometryTolerance ...
    && ...
    abs(xMeshMax-xMaxExpected) < geometryTolerance ...
    && ...
    abs(yMeshMin-yMinExpected) < geometryTolerance ...
    && ...
    abs(yMeshMax-yMaxExpected) < geometryTolerance ...
    && ...
    abs(zMeshMin-zMinExpected) < geometryTolerance ...
    && ...
    abs(zMeshMax-zMaxExpected) < geometryTolerance;


if ~geometryIsCorrect

    fprintf('\n')
    fprintf('================================================\n')
    fprintf('WRONG 3D GEOMETRY DETECTED\n')
    fprintf('================================================\n')
    fprintf('\n')
    fprintf('This script expects:\n')
    fprintf('  x = -0.300 to +0.300 m\n')
    fprintf('  y = -0.150 to +0.150 m\n')
    fprintf('  z =  0.000 to +0.200 m\n')
    fprintf('\n')
    fprintf('The loaded data instead has:\n')
    fprintf('  x = %.6f to %.6f m\n',xMeshMin,xMeshMax)
    fprintf('  y = %.6f to %.6f m\n',yMeshMin,yMeshMax)
    fprintf('  z = %.6f to %.6f m\n',zMeshMin,zMeshMax)
    fprintf('\n')

    error( ...
        ['This is not the corrected rectangular experimental output. ' ...
         'Do not process the old cylindrical simulation.'])

end


fprintf('RECTANGULAR GEOMETRY CHECK PASSED.\n\n')


%% ================================================================
%  TETRAHEDRON CENTRES + VOLUMES
%
%  DG0 has one concentration value per tetrahedron.


P1 = geometry(tetra(:,1),:);
P2 = geometry(tetra(:,2),:);
P3 = geometry(tetra(:,3),:);
P4 = geometry(tetra(:,4),:);


cellCentre = ...
    (P1 + P2 + P3 + P4) ...
    / 4;


v21 = P2-P1;
v31 = P3-P1;
v41 = P4-P1;


cellVolume = abs( ...
    dot( ...
        v21, ...
        cross(v31,v41,2), ...
        2)) ...
    / 6;


xCell = cellCentre(:,1);
yCell = cellCentre(:,2);
zCell = cellCentre(:,3);


meshVolume = sum(cellVolume);

exactVolume = ...
    L ...
    * ...
    W ...
    * ...
    H;


fprintf('Tank-volume check:\n')
fprintf('  mesh volume  = %.12e m^3\n',meshVolume)
fprintf('  exact volume = %.12e m^3\n',exactVolume)
fprintf('  error        = %.6e %%\n\n', ...
    100*abs(meshVolume-exactVolume)/exactVolume)


%% ================================================================
%  VERTICAL BINS FOR HORIZONTAL AVERAGING


zEdges = linspace( ...
    0, ...
    H, ...
    nZBins+1);


zAverage = 0.5*( ...
    zEdges(1:end-1) ...
    + ...
    zEdges(2:end));


zAverage = zAverage(:);


cellLayer = discretize( ...
    zCell, ...
    zEdges);


validCells = ...
    ~isnan(cellLayer) ...
    & ...
    cellLayer >= 1 ...
    & ...
    cellLayer <= nZBins;


layerVolume = accumarray( ...
    cellLayer(validCells), ...
    cellVolume(validCells), ...
    [nZBins 1], ...
    @sum, ...
    0);


% Central 6 cm x 6 cm region, useful for looking at the plume
% without the huge outer ambient dominating the mean.

centralMask = ...
    abs(xCell) <= centralHalfWidthX ...
    & ...
    abs(yCell) <= centralHalfWidthY;


validCentral = ...
    validCells ...
    & ...
    centralMask;


centralLayerVolume = accumarray( ...
    cellLayer(validCentral), ...
    cellVolume(validCentral), ...
    [nZBins 1], ...
    @sum, ...
    0);


if any(layerVolume == 0)

    error( ...
        ['At least one full-tank z-bin has no cell centres. ' ...
         'Reduce nZBins.'])

end


if any(centralLayerVolume == 0)

    warning( ...
        ['Some central-region z-bins contain no cells. ' ...
         'Central mean will contain NaNs there.'])

end


%% ================================================================
%  CHOOSE SAVED FIELDS CLOSEST TO REQUESTED TIMES


requestedTimes = requestedTimes( ...
    requestedTimes <= times(end)+1e-9);


if isempty(requestedTimes)

    requestedTimes = times(end);

end


nSelected = numel(requestedTimes);

selectedIndices = zeros(nSelected,1);
selectedTimes = zeros(nSelected,1);


fprintf('Selected plotting times:\n')


for j = 1:nSelected

    [~,selectedIndices(j)] = min( ...
        abs(times-requestedTimes(j)));

    selectedTimes(j) = ...
        times(selectedIndices(j));

    fprintf( ...
        '  requested %.3f s -> saved %.6f s\n', ...
        requestedTimes(j), ...
        selectedTimes(j));

end


fprintf('\n')


%% ================================================================
%  STORAGE


cBarAll = nan( ...
    nZBins, ...
    nTimes);


cBarCentral = nan( ...
    nZBins, ...
    nTimes);


freshVolume = nan( ...
    nTimes, ...
    1);


cMinimum = nan( ...
    nTimes, ...
    1);


cMaximum = nan( ...
    nTimes, ...
    1);


%% ================================================================
%  VISUAL SLICE GRIDS


xXZ = linspace( ...
    -L/2, ...
    L/2, ...
    nxXZ);


zXZ = linspace( ...
    0, ...
    H, ...
    nzXZ);


[XXZ,ZXZ] = meshgrid( ...
    xXZ, ...
    zXZ);


yYZ = linspace( ...
    -W/2, ...
    W/2, ...
    nyYZ);


zYZ = linspace( ...
    0, ...
    H, ...
    nzYZ);


[YYZ,ZYZ] = meshgrid( ...
    yYZ, ...
    zYZ);


%% ================================================================
%  LOOP THROUGH SAVED CONCENTRATION FIELDS


fprintf('Processing concentration fields...\n\n')


for k = 1:nTimes

    cCell = h5read( ...
        h5File, ...
        datasetPaths{k});


    cCell = double(cCell(:));


    if numel(cCell) ~= nCells

        error( ...
            ['Field at t = %.6f s has %d values, ' ...
             'but mesh has %d tetrahedra.'], ...
            times(k), ...
            numel(cCell), ...
            nCells)

    end


    cMinimum(k) = min(cCell);
    cMaximum(k) = max(cCell);


    %% ------------------------------------------------------------
    %  FULL-TANK VOLUME-WEIGHTED HORIZONTAL MEAN


    weightedFull = accumarray( ...
        cellLayer(validCells), ...
        cCell(validCells).*cellVolume(validCells), ...
        [nZBins 1], ...
        @sum, ...
        0);


    cBarAll(:,k) = ...
        weightedFull ...
        ./ ...
        layerVolume;


    %% ------------------------------------------------------------
    %  CENTRAL 6 cm x 6 cm MEAN


    weightedCentral = accumarray( ...
        cellLayer(validCentral), ...
        cCell(validCentral).*cellVolume(validCentral), ...
        [nZBins 1], ...
        @sum, ...
        0);


    goodCentralBins = ...
        centralLayerVolume > 0;


    cBarCentral(goodCentralBins,k) = ...
        weightedCentral(goodCentralBins) ...
        ./ ...
        centralLayerVolume(goodCentralBins);


    %% ------------------------------------------------------------
    %  TOTAL FRESH-WATER VOLUME


    freshVolume(k) = sum( ...
        (1-cCell) ...
        .* ...
        cellVolume);


    %% ------------------------------------------------------------
    %  CENTRAL x-z AND y-z SLICES AT SELECTED TIMES


    selectedPosition = find( ...
        selectedIndices == k, ...
        1);


    if ~isempty(selectedPosition)

        fprintf( ...
            '  making slices at t = %.3f s\n', ...
            times(k));



        % x-z plane: thin slab around y = 0


        xzMask = ...
            abs(yCell) ...
            <= ...
            sliceHalfThicknessXZ;


        F_xz = scatteredInterpolant( ...
            xCell(xzMask), ...
            zCell(xzMask), ...
            cCell(xzMask), ...
            'linear', ...
            'nearest');


        Cxz = F_xz( ...
            XXZ, ...
            ZXZ);


        % Plotting only: suppress solver roundoff such as 1+1e-8.
        Cxz = max( ...
            0, ...
            min(1,Cxz));


        fig = figure( ...
            'Color','w', ...
            'Visible','off', ...
            'Units','pixels', ...
            'Position',[100 100 1800 600]);


        ax = axes( ...
            'Parent',fig, ...
            'Units','normalized', ...
            'Position',[0 0 1 1]);


        imagesc( ...
            ax, ...
            xXZ, ...
            zXZ, ...
            Cxz);


        set(ax,'YDir','normal');

        clim(ax,[0 1]);

        colormap( ...
            ax, ...
            flipud(gray(256)));


        xlim(ax,[-L/2 L/2]);
        ylim(ax,[0 H]);


        % CRITICAL:
        % preserve physical geometry:
        %
        % 0.60 m wide / 0.20 m high = 3:1.
        axis(ax,'image');
        axis(ax,'off');


        timeTag = strrep( ...
            sprintf('%05.2f',times(k)), ...
            '.', ...
            'p');


        exportgraphics( ...
            ax, ...
            fullfile( ...
                xzFolder, ...
                ['xz_t_' timeTag 's.png']), ...
            'Resolution',pngResolution, ...
            'BackgroundColor','white');



        % THESIS-READY CONTRAST VERSION
        %
        % Same field and same physical proportions, but display
        % only the upper concentration range 0.97 <= c <= 1.
        % Values below 0.97 saturate at the fresh-water end of the
        % greyscale, making weak plume structure much clearer.


        clim( ...
            ax, ...
            [contrastLower 1]);


        exportgraphics( ...
            ax, ...
            fullfile( ...
                xzContrastFolder, ...
                ['xz_contrast_0p97_t_' timeTag 's.png']), ...
            'Resolution',thesisPngResolution, ...
            'BackgroundColor','white');


        close(fig)



        % y-z plane: thin slab around x = 0


        yzMask = ...
            abs(xCell) ...
            <= ...
            sliceHalfThicknessYZ;


        F_yz = scatteredInterpolant( ...
            yCell(yzMask), ...
            zCell(yzMask), ...
            cCell(yzMask), ...
            'linear', ...
            'nearest');


        Cyz = F_yz( ...
            YYZ, ...
            ZYZ);


        Cyz = max( ...
            0, ...
            min(1,Cyz));


        fig = figure( ...
            'Color','w', ...
            'Visible','off', ...
            'Units','pixels', ...
            'Position',[100 100 1200 800]);


        ax = axes( ...
            'Parent',fig, ...
            'Units','normalized', ...
            'Position',[0 0 1 1]);


        imagesc( ...
            ax, ...
            yYZ, ...
            zYZ, ...
            Cyz);


        set(ax,'YDir','normal');

        clim(ax,[0 1]);

        colormap( ...
            ax, ...
            flipud(gray(256)));


        xlim(ax,[-W/2 W/2]);
        ylim(ax,[0 H]);


        % 0.30 m wide / 0.20 m high = 1.5:1.
        axis(ax,'image');
        axis(ax,'off');


        exportgraphics( ...
            ax, ...
            fullfile( ...
                yzFolder, ...
                ['yz_t_' timeTag 's.png']), ...
            'Resolution',pngResolution, ...
            'BackgroundColor','white');


        % Thesis-ready 0.97 contrast version.
        clim( ...
            ax, ...
            [contrastLower 1]);


        exportgraphics( ...
            ax, ...
            fullfile( ...
                yzContrastFolder, ...
                ['yz_contrast_0p97_t_' timeTag 's.png']), ...
            'Resolution',thesisPngResolution, ...
            'BackgroundColor','white');


        close(fig)

    end


    if ...
        k == 1 ...
        || ...
        mod(k,10) == 0 ...
        || ...
        k == nTimes

        fprintf( ...
            '  processed %3d / %3d   t = %.3f s\n', ...
            k, ...
            nTimes, ...
            times(k));

    end

end


fprintf('\nAll saved fields processed.\n\n')


%% ================================================================
%  FINAL-TIME HORIZONTAL x-y PLAN SLICES


cFinal = h5read( ...
    h5File, ...
    datasetPaths{end});


cFinal = double(cFinal(:));


xXY = linspace( ...
    -L/2, ...
    L/2, ...
    nxXY);


yXY = linspace( ...
    -W/2, ...
    W/2, ...
    nyXY);


[XXY,YXY] = meshgrid( ...
    xXY, ...
    yXY);


for j = 1:numel(planZFractions)

    zFraction = planZFractions(j);

    zTarget = ...
        zFraction ...
        * ...
        H;


    xyMask = ...
        abs(zCell-zTarget) ...
        <= ...
        sliceHalfThicknessXY;


    if nnz(xyMask) < 50

        warning( ...
            'Too few cells for x-y slice at z/H = %.2f.', ...
            zFraction)

        continue

    end


    F_xy = scatteredInterpolant( ...
        xCell(xyMask), ...
        yCell(xyMask), ...
        cFinal(xyMask), ...
        'linear', ...
        'nearest');


    Cxy = F_xy( ...
        XXY, ...
        YXY);


    Cxy = max( ...
        0, ...
        min(1,Cxy));


    fig = figure( ...
        'Color','w', ...
        'Visible','off', ...
        'Units','pixels', ...
        'Position',[100 100 1600 800]);


    ax = axes( ...
        'Parent',fig, ...
        'Units','normalized', ...
        'Position',[0 0 1 1]);


    imagesc( ...
        ax, ...
        xXY, ...
        yXY, ...
        Cxy);


    set(ax,'YDir','normal');

    clim(ax,[0 1]);

    colormap( ...
        ax, ...
        flipud(gray(256)));


    xlim(ax,[-L/2 L/2]);
    ylim(ax,[-W/2 W/2]);


    % 0.60 m long / 0.30 m wide = 2:1.
    axis(ax,'image');
    axis(ax,'off');


    zTag = strrep( ...
        sprintf('%0.2f',zFraction), ...
        '.', ...
        'p');


    exportgraphics( ...
        ax, ...
        fullfile( ...
            xyFolder, ...
            ['xy_final_zOverH_' zTag '.png']), ...
        'Resolution',pngResolution, ...
        'BackgroundColor','white');


    % Thesis-ready 0.97 contrast version.
    clim( ...
        ax, ...
        [contrastLower 1]);


    exportgraphics( ...
        ax, ...
        fullfile( ...
            xyContrastFolder, ...
            ['xy_final_contrast_0p97_zOverH_' zTag '.png']), ...
        'Resolution',thesisPngResolution, ...
        'BackgroundColor','white');


    close(fig)

end


%% ================================================================
%  SELECTED-TIME FULL-TANK MEAN PROFILES


cBarSelected = ...
    cBarAll(:,selectedIndices);


% Pale pink -> dark red.
profileColors = [ ...
    ones(nSelected,1), ...
    linspace(0.72,0.00,nSelected)', ...
    linspace(0.72,0.00,nSelected)' ...
    ];



% CLEAN THESIS-STYLE PROFILE FIGURE


fig = figure( ...
    'Color','w', ...
    'Visible','off', ...
    'Units','pixels', ...
    'Position',[100 100 900 1200]);


ax = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',[0 0 1 1]);


hold(ax,'on')


for j = 1:nSelected

    plot( ...
        ax, ...
        cBarSelected(:,j), ...
        zAverage/H, ...
        'LineWidth',4.0, ...
        'Color',profileColors(j,:));

end


allSelected = cBarSelected(:);
allSelected = allSelected(isfinite(allSelected));


if isempty(allSelected)

    xLower = 0.99;

else

    cMinSelected = min(allSelected);

    deviation = max( ...
        1-cMinSelected, ...
        1e-6);

    xLower = max( ...
        0, ...
        cMinSelected ...
        - ...
        0.10*deviation);

end


xlim(ax,[xLower 1]);
ylim(ax,[0 1]);

axis(ax,'off');


exportgraphics( ...
    ax, ...
    fullfile( ...
        resultsFolder, ...
        'full_tank_average_selected_times_clean.png'), ...
    'Resolution',600, ...
    'BackgroundColor','white');


close(fig)


%% ================================================================
%  LABELLED FULL-TANK MEAN PROFILES


fig = figure( ...
    'Color','w', ...
    'Visible','off', ...
    'Units','pixels', ...
    'Position',[100 100 800 1000]);


ax = axes( ...
    'Parent',fig);


hold(ax,'on')


for j = 1:nSelected

    plot( ...
        ax, ...
        cBarSelected(:,j), ...
        zAverage/H, ...
        'LineWidth',2.5, ...
        'Color',profileColors(j,:));

end


xlabel( ...
    '$\overline{c}$', ...
    'Interpreter','latex');


ylabel( ...
    '$z/H$', ...
    'Interpreter','latex');


xlim(ax,[xLower 1]);
ylim(ax,[0 1]);


set(ax, ...
    'FontSize',14, ...
    'LineWidth',1.2, ...
    'Box','on');


exportgraphics( ...
    fig, ...
    fullfile( ...
        resultsFolder, ...
        'full_tank_average_selected_times_labelled.png'), ...
    'Resolution',300);


close(fig)


%% ================================================================
%  CENTRAL 6 cm x 6 cm MEAN PROFILES
%
%  Useful for seeing plume evolution before global stratification
%  becomes appreciable across the full 60 x 30 cm tank.


centralSelected = ...
    cBarCentral(:,selectedIndices);


fig = figure( ...
    'Color','w', ...
    'Visible','off', ...
    'Units','pixels', ...
    'Position',[100 100 800 1000]);


ax = axes( ...
    'Parent',fig);


hold(ax,'on')


for j = 1:nSelected

    plot( ...
        ax, ...
        centralSelected(:,j), ...
        zAverage/H, ...
        'LineWidth',2.5, ...
        'Color',profileColors(j,:));

end


xlabel( ...
    '$\overline{c}_{\mathrm{centre}}$', ...
    'Interpreter','latex');


ylabel( ...
    '$z/H$', ...
    'Interpreter','latex');


xlim(ax,[0 1]);
ylim(ax,[0 1]);


set(ax, ...
    'FontSize',14, ...
    'LineWidth',1.2, ...
    'Box','on');


exportgraphics( ...
    fig, ...
    fullfile( ...
        resultsFolder, ...
        'central_region_average_selected_times.png'), ...
    'Resolution',300);


close(fig)


%% ================================================================
%  TIME-HEIGHT MAP: FULL-TANK MEAN CONCENTRATION


fig = figure( ...
    'Color','w', ...
    'Visible','off', ...
    'Units','pixels', ...
    'Position',[100 100 1200 800]);


ax = axes( ...
    'Parent',fig);


imagesc( ...
    ax, ...
    times, ...
    zAverage/H, ...
    cBarAll);


set(ax,'YDir','normal');

clim(ax,[0 1]);

colormap( ...
    ax, ...
    flipud(gray(256)));


xlabel( ...
    '$t$ (s)', ...
    'Interpreter','latex');


ylabel( ...
    '$z/H$', ...
    'Interpreter','latex');


cb = colorbar(ax);


ylabel( ...
    cb, ...
    '$\overline{c}$', ...
    'Interpreter','latex');


set(ax, ...
    'FontSize',14, ...
    'LineWidth',1.2);


exportgraphics( ...
    fig, ...
    fullfile( ...
        resultsFolder, ...
        'full_tank_average_time_height.png'), ...
    'Resolution',300);


close(fig)


%% ================================================================
%  TIME-HEIGHT MAP: FULL-TANK MEAN FRESH-WATER FRACTION
%
%      fbar = 1-cbar


freshMean = ...
    1 ...
    - ...
    cBarAll;


fig = figure( ...
    'Color','w', ...
    'Visible','off', ...
    'Units','pixels', ...
    'Position',[100 100 1200 800]);


ax = axes( ...
    'Parent',fig);


imagesc( ...
    ax, ...
    times, ...
    zAverage/H, ...
    freshMean);


set(ax,'YDir','normal');

colormap(ax,gray(256));


xlabel( ...
    '$t$ (s)', ...
    'Interpreter','latex');


ylabel( ...
    '$z/H$', ...
    'Interpreter','latex');


cb = colorbar(ax);


ylabel( ...
    cb, ...
    '$1-\overline{c}$', ...
    'Interpreter','latex');


set(ax, ...
    'FontSize',14, ...
    'LineWidth',1.2);


exportgraphics( ...
    fig, ...
    fullfile( ...
        resultsFolder, ...
        'full_tank_mean_fresh_fraction_time_height.png'), ...
    'Resolution',300);


close(fig)


%% ================================================================
%  GLOBALLY NORMALISED FRESH-WATER DEFICIT
%
%  Normalise ONCE over all z and t.
%  This retains relative strength between times.


maxFreshMean = max( ...
    freshMean(:), ...
    [], ...
    'omitnan');


if maxFreshMean > 0

    freshMeanNormalised = ...
        freshMean ...
        / ...
        maxFreshMean;

else

    freshMeanNormalised = ...
        zeros(size(freshMean));

end


fig = figure( ...
    'Color','w', ...
    'Visible','off', ...
    'Units','pixels', ...
    'Position',[100 100 1200 800]);


ax = axes( ...
    'Parent',fig);


imagesc( ...
    ax, ...
    times, ...
    zAverage/H, ...
    freshMeanNormalised);


set(ax,'YDir','normal');

clim(ax,[0 1]);

colormap(ax,gray(256));


xlabel( ...
    '$t$ (s)', ...
    'Interpreter','latex');


ylabel( ...
    '$z/H$', ...
    'Interpreter','latex');


cb = colorbar(ax);


ylabel( ...
    cb, ...
    'normalised $1-\overline{c}$', ...
    'Interpreter','latex');


set(ax, ...
    'FontSize',14, ...
    'LineWidth',1.2);


exportgraphics( ...
    fig, ...
    fullfile( ...
        resultsFolder, ...
        'full_tank_normalised_fresh_deficit_time_height.png'), ...
    'Resolution',300);


close(fig)


%% ================================================================
%  FRESH-WATER VOLUME VERSUS TIME


fig = figure( ...
    'Color','w', ...
    'Visible','off', ...
    'Units','pixels', ...
    'Position',[100 100 1000 650]);


ax = axes( ...
    'Parent',fig);


plot( ...
    ax, ...
    times, ...
    freshVolume, ...
    'k-', ...
    'LineWidth',2.2);


xlabel( ...
    '$t$ (s)', ...
    'Interpreter','latex');


ylabel( ...
    '$V_{\mathrm{fresh}}$ (m$^3$)', ...
    'Interpreter','latex');


set(ax, ...
    'FontSize',14, ...
    'LineWidth',1.2, ...
    'Box','on');


exportgraphics( ...
    fig, ...
    fullfile( ...
        resultsFolder, ...
        'fresh_water_volume_vs_time.png'), ...
    'Resolution',300);


close(fig)


%% ================================================================
%  SAVE MAT DATA


save( ...
    fullfile( ...
        resultsFolder, ...
        'rectangular_3D_postprocessing_data.mat'), ...
    'times', ...
    'zAverage', ...
    'zEdges', ...
    'cBarAll', ...
    'cBarCentral', ...
    'freshMean', ...
    'freshMeanNormalised', ...
    'freshVolume', ...
    'cMinimum', ...
    'cMaximum', ...
    'layerVolume', ...
    'L', ...
    'W', ...
    'H', ...
    'selectedTimes');


%% ================================================================
%  SAVE LONG-FORM CSV


nRows = ...
    nTimes ...
    * ...
    nZBins;


timeColumn = zeros(nRows,1);
zColumn = zeros(nRows,1);
cMeanColumn = zeros(nRows,1);
centralMeanColumn = zeros(nRows,1);
freshMeanColumn = zeros(nRows,1);


rowStart = 1;


for k = 1:nTimes

    rows = ...
        rowStart:(rowStart+nZBins-1);


    timeColumn(rows) = ...
        times(k);


    zColumn(rows) = ...
        zAverage/H;


    cMeanColumn(rows) = ...
        cBarAll(:,k);


    centralMeanColumn(rows) = ...
        cBarCentral(:,k);


    freshMeanColumn(rows) = ...
        freshMean(:,k);


    rowStart = ...
        rowStart ...
        + ...
        nZBins;

end


profileTable = table( ...
    timeColumn, ...
    zColumn, ...
    cMeanColumn, ...
    centralMeanColumn, ...
    freshMeanColumn, ...
    'VariableNames', ...
    { ...
    'time_s', ...
    'z_over_H', ...
    'c_mean_full_tank', ...
    'c_mean_central_region', ...
    'fresh_fraction_mean' ...
    });


writetable( ...
    profileTable, ...
    fullfile( ...
        resultsFolder, ...
        'rectangular_3D_horizontal_average_all_times.csv'));


%% ================================================================
%  SAVE GLOBAL TIME-SERIES CSV


timeTable = table( ...
    times, ...
    freshVolume, ...
    cMinimum, ...
    cMaximum, ...
    'VariableNames', ...
    { ...
    'time_s', ...
    'fresh_volume_m3', ...
    'c_min', ...
    'c_max' ...
    });


writetable( ...
    timeTable, ...
    fullfile( ...
        resultsFolder, ...
        'rectangular_3D_global_time_series.csv'));


%% ================================================================
%  SUMMARY


fprintf('\n')
fprintf('================================================\n')
fprintf('RECTANGULAR 3D POST-PROCESSING COMPLETE\n')
fprintf('================================================\n')
fprintf('\n')
fprintf('Domain processed:\n')
fprintf('  L = %.3f m\n',L)
fprintf('  W = %.3f m\n',W)
fprintf('  H = %.3f m\n',H)
fprintf('\n')
fprintf('Processed %d saved concentration fields.\n',nTimes)
fprintf('Final saved time = %.3f s\n',times(end))
fprintf('Vertical bins = %d\n',nZBins)
fprintf('Final fresh-water volume = %.8e m^3\n',freshVolume(end))
fprintf('Overall concentration range = %.10g to %.10g\n', ...
    min(cMinimum), ...
    max(cMaximum))
fprintf('\n')
fprintf('Results saved in:\n%s\n',resultsFolder)
fprintf('\n')
fprintf('Main image folders:\n')
fprintf('  %s\n',xzFolder)
fprintf('  %s\n',yzFolder)
fprintf('  %s\n',xyFolder)
fprintf('\n')
fprintf('Thesis-ready 0.97 contrast folders:\n')
fprintf('  %s\n',xzContrastFolder)
fprintf('  %s\n',yzContrastFolder)
fprintf('  %s\n',xyContrastFolder)
fprintf('================================================\n')
fprintf('\n')
